=== fergodani/LEW/XML/Ejercicio_2/XML/esquema.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="biblioteca">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="color" />
				<xs:element ref="color" />
				<xs:element ref="color" />
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="autor" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>
    <xs:element name="autor">
		<xs:complexType>
			<xs:sequence>
                <xs:element ref="imagen"/>
				<xs:element minOccurs="1" maxOccurs="unbounded" ref="libro" />
			</xs:sequence>
            <xs:attribute name="nombre" type="xs:string" use="required" />
			<xs:attribute name="nacimiento" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>
    <xs:element name="libro">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="titulo" type="xs:string"/>
                <xs:element name="editorial" type="xs:string"/>
                <xs:element name="salida" type="xs:integer"/>
                <xs:element name="sinopsis" type="xs:string"/>
                <xs:element name="puntuacion" type="xs:decimal"/>
                <xs:element name="isbn" type="xs:string"/>
                <xs:element name="genero" type="xs:string"/>
                <xs:element ref="imagen"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="imagen">
        <xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:pattern value="[a-zA-Z]*[1-9]*(\.jpg|\.png)"/>
			</xs:restriction>
		</xs:simpleType>
    </xs:element>
    <xs:element name="color">
        <xs:simpleType>
	    		<xs:restriction base="xs:string">
	    			<xs:pattern value="#([a-fA-F0-9]{6}|[a-fA-F0-9]{3})"/>
	    		</xs:restriction>
	    	</xs:simpleType>
        </xs:element>
</xs:schema>

=== fergodani/LEW/XML/Ejercicio_2/XML/romance.xml
<?xml version="1.0" encoding="utf-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="esquema.xsd">
    <cabecera>Autores de Romance</cabecera>
    <color>#FAC8FF</color>
    <color>#FEF4FF</color>
    <color>#000000</color>
     <autor nombre="Nicholas Sparks" nacimiento="31 de diciembre de 1965">
        <imagen>nicholasSparks.jpg</imagen>
        <libro>
            <titulo>El cuaderno de Noah</titulo>
            <editorial>Roca Editorial</editorial>
            <salida>1996</salida>
            <sinopsis>La historia de amor entre Noah y Allie que trasciende el tiempo.</sinopsis>
            <puntuacion>4.5</puntuacion>
            <isbn>978-84-95763-44-8</isbn>
            <genero>Romance</genero>
            <imagen>cuadernoNoah.jpg</imagen>
        </libro>
        <libro>
            <titulo>Querido John</titulo>
            <editorial>Roca Editorial</editorial>
            <salida>2006</salida>
            <sinopsis>La carta de John a Savannah desencadena una emotiva historia de amor y sacrificio.</sinopsis>
            <puntuacion>4.4</puntuacion>
            <isbn>978-84-96924-73-0</isbn>
            <genero>Romance</genero>
            <imagen>queridoJohn.jpg</imagen>
        </libro>
    </autor>
    <autor nombre="Jane Austen" nacimiento="16 de diciembre de 1775">
        <imagen>janeAusten.jpg</imagen>
        <libro>
            <titulo>Orgullo y prejuicio</titulo>
            <editorial>Alianza Editorial</editorial>
            <salida>1813</salida>
            <sinopsis>La historia de Elizabeth Bennet y Mr. Darcy en la Inglaterra del siglo XIX.</sinopsis>
            <puntuacion>4.6</puntuacion>
            <isbn>978-84-206-3279-1</isbn>
            <genero>Romance</genero>
            <imagen>orgulloPrejuicio.jpg</imagen>
        </libro>
        <libro>
            <titulo>Sentido y sensibilidad</titulo>
            <editorial>Alianza Editorial</editorial>
            <salida>1811</salida>
            <sinopsis>Las vidas y amores de las hermanas Dashwood en la sociedad británica.</sinopsis>
            <puntuacion>4.5</puntuacion>
            <isbn>978-84-206-3249-4</isbn>
            <genero>Romance</genero>
            <imagen>sentidoSensibilidad.jpg</imagen>
        </libro>
    </autor>
    <autor nombre="Jojo Moyes" nacimiento="4 de agosto de 1969">
        <imagen>jojoMoyes.jpg</imagen>
        <libro>
            <titulo>Yo antes de ti</titulo>
            <editorial>Penguin Random House</editorial>
            <salida>2012</salida>
            <sinopsis>La historia de amor entre Louisa y Will, un hombre tetrapléjico.</sinopsis>
            <puntuacion>4.7</puntuacion>
            <isbn>978-84-08-09753-3</isbn>
            <genero>Romance</genero>
            <imagen>yoAntesDeTi.jpg</imagen>
        </libro>
    </autor>
</biblioteca>

=== fergodani/LEW/XML/Ejercicio_2/XML/scifi.xml
<?xml version="1.0" encoding="utf-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="esquema.xsd">
    <color>#002439</color>
    <color>#E4EFF0</color>
    <color>#ffffff</color>
    <autor nombre="Isaac Asimov" nacimiento="2 de enero de 1920">
        <imagen>asimov.jpg</imagen>
        <libro>
            <titulo>Fundación</titulo>
            <editorial>Ediciones B</editorial>
            <salida>1951</salida>
            <sinopsis>La saga de la Fundación para preservar el conocimiento en una galaxia en declive.</sinopsis>
            <puntuacion>4.7</puntuacion>
            <isbn>978-84-666-4667-2</isbn>
            <genero>Ciencia Ficción</genero>
            <imagen>fundacion.jpg</imagen>
        </libro>
        <libro>
            <titulo>Yo, Robot</titulo>
            <editorial>Ediciones B</editorial>
            <salida>1950</salida>
            <sinopsis>Relatos sobre robots y su interacción con los humanos.</sinopsis>
            <puntuacion>4.6</puntuacion>
            <isbn>978-84-666-3962-0</isbn>
            <genero>Ciencia Ficción</genero>
            <imagen>yoRobot.jpg</imagen>
        </libro>
    </autor>
    <autor nombre="Philip K. Dick" nacimiento="16 de diciembre de 1928">
        <imagen>philipDick.jpg</imagen>
        <libro>
            <titulo>Blade Runner (¿Sueñan los androides con ovejas eléctricas?)</titulo>
            <editorial>Minotauro</editorial>
            <salida>1968</salida>
            <sinopsis>La historia de Rick Deckard, cazador de androides, en un mundo postapocalíptico.</sinopsis>
            <puntuacion>4.5</puntuacion>
            <isbn>978-84-450-7429-1</isbn>
            <genero>Ciencia Ficción</genero>
            <imagen>bladeRunner.jpg</imagen>
        </libro>
    </autor>
    <autor nombre="Arthur C. Clarke" nacimiento="16 de diciembre de 1917">
        <imagen>arthurClarke.jpg</imagen>
        <libro>
            <titulo>2001: Una odisea espacial</titulo>
            <editorial>Debolsillo</editorial>
            <salida>1968</salida>
            <sinopsis>La exploración del espacio y el encuentro con una inteligencia extraterrestre.</sinopsis>
            <puntuacion>4.8</puntuacion>
            <isbn>978-84-8346-406-8</isbn>
            <genero>Ciencia Ficción</genero>
            <imagen>odiseaEspacial.jpg</imagen>
        </libro>
    </autor>
</biblioteca>

=== fergodani/LEW/XML/Ejercicio_2/XML/fantasia.xml
<?xml version="1.0" encoding="utf-8"?>
<biblioteca xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="esquema.xsd">
    <color>#376d60</color>
    <color>#abd2a3</color>
    <color>#ffffff</color>
    <autor nombre="J.K. Rowling" nacimiento="31 de julio de 1965">
        <imagen>JKRowling.jpg</imagen>
        <libro>
            <titulo>Harry Potter y la piedra filosofal</titulo>
            <editorial>Salamandra</editorial>
            <salida>1997</salida>
            <sinopsis>La historia del joven mago Harry Potter.</sinopsis>
            <puntuacion>4.8</puntuacion>
            <isbn>978-84-9838-235-2</isbn>
            <genero>Fantasía</genero>
            <imagen>harryPotter.jpg</imagen>
        </libro>
        <libro>
            <titulo>Harry Potter y la cámara secreta</titulo>
            <editorial>Salamandra</editorial>
            <salida>1998</salida>
            <sinopsis>La segunda aventura de Harry Potter en Hogwarts.</sinopsis>
            <puntuacion>4.7</puntuacion>
            <isbn>978-84-9838-236-9</isbn>
            <genero>Fantasía</genero>
            <imagen>harryPotter2.jpg</imagen>
        </libro>
    </autor>
    <autor nombre="J.R.R. Tolkien" nacimiento="3 de enero de 1892">
        <imagen>tolkien.jpg</imagen>
        <libro>
            <titulo>El Señor de los Anillos</titulo>
            <editorial>Minotauro</editorial>
            <salida>1954</salida>
            <sinopsis>La épica historia de la lucha por el Anillo Único en la Tierra Media.</sinopsis>
            <puntuacion>4.9</puntuacion>
            <isbn>978-84-450-7175-7</isbn>
            <genero>Fantasía</genero>
            <imagen>senorAnillos.jpg</imagen>
        </libro>
        <libro>
            <titulo>El Hobbit</titulo>
            <editorial>Minotauro</editorial>
            <salida>1937</salida>
            <sinopsis>La historia de Bilbo Bolsón y su aventura para reclamar un tesoro.</sinopsis>
            <puntuacion>4.7</puntuacion>
            <isbn>978-84-450-7173-3</isbn>
            <genero>Fantasía</genero>
            <imagen>hobbit.jpg</imagen>
        </libro>
    </autor>
    <autor nombre="George R.R. Martin" nacimiento="20 de septiembre de 1948">
        <imagen>georgeMartin.jpg</imagen>
        <libro>
            <titulo>Juego de Tronos</titulo>
            <editorial>Plaza y Janés</editorial>
            <salida>1996</salida>
            <sinopsis>La lucha por el Trono de Hierro en los Siete Reinos.</sinopsis>
            <puntuacion>4.6</puntuacion>
            <isbn>978-84-01-33655-8</isbn>
            <genero>Fantasía</genero>
            <imagen>juegoTronos.jpg</imagen>
        </libro>
        <libro>
            <titulo>Choque de Reyes</titulo>
            <editorial>Plaza y Janés</editorial>
            <salida>1998</salida>
            <sinopsis>Continúa la saga de luchas políticas y guerras en Poniente.</sinopsis>
            <puntuacion>4.5</puntuacion>
            <isbn>978-84-01-35239-6</isbn>
            <genero>Fantasía</genero>
            <imagen>choqueReyes.jpg</imagen>
        </libro>
    </autor>
</biblioteca>
